version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/app
      - ./backend/node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      .env.dev
    depends_on:
      - db
    networks:
      - wikideas-network
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      .env.dev
    ports:
      - '27017:27017'
    networks:
      - wikideas-network

networks:
  wikideas-network:
    driver: bridge